# Generated by Django 4.2.11 on 2024-05-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0006_customer_order_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='product',
            new_name='products',
        ),
    ]
