# Generated by Django 4.2.11 on 2024-05-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0007_rename_product_ordereditem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='products',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_carts', to='toolhub.product'),
        ),
    ]
