# Generated by Django 4.2.11 on 2024-05-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0008_remove_ordereditem_products_ordereditem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='toolhub.order'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_carts', to='toolhub.product'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
